config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  resources :bookings, only: [:new, :create, :index]

  get 'ca', to: 'pages#ca'
  get 'a-propos-de-nous', to: 'pages#about'

  match '/send_mail', to: 'contact#send_mail', via: 'post'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :start_time,
    :uniqueness => {:message => "Cette plage horaire n'est pas disponible. Veuillez SVP en choisir une autre."}

  validate :start_date_in_future, on: :create

  def start_date_in_future
    if start_time < Date.current
      errors.add(:start_time, "Vous avez choisi une date antérieure. Veuillez SVP en choisir une autre.")
    end
  end


end

app/models/schedule_time_slot.rb
class ScheduleTimeSlot < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  respond_to :html

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.save
    if @booking.persisted?
      BookingMailer.with(booking: @booking).booking_email.deliver_later
      flash[:notice] = "Votre rendez-vous a été ajouté à l'horaire! À bientôt."
      redirect_to bookings_path
    else
      respond_with(@booking)
    end
  end

  def destroy
    if admin_user_signed_in?
      @booking = Booking.find(params[:id])
      @booking.destroy
      redirect_to admin_root_path
    end
  end

  private

    def booking_params
      params.require(:booking).permit(:name, :start_time, :email, :phone)
    end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def send_mail
    name = params[:name]
    address = params[:address]
    phone = params[:phone]
    email = params[:email]
    message = params[:message]
    ContactMailer.contact_email(name, address, phone, email, message).deliver_now
    flash[:notice] = "Votre message a été envoyé. Nous vous contacterons sous peu."
    redirect_to root_path(anchor: 'contact_form')
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def ca
  end

  def about
    @images = Dir.chdir(Rails.root.join('app/assets/images')) do
      Dir.glob("carousel/*.png")
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/admin/dashboard/_calendar.haml
.container
  .simple-calendar
    - @bookings = Booking.all
    = week_calendar events: @bookings do |date, bookings|
      = date
      - bookings.each do |booking|
        %div
          .booking-information
            %strong= booking.start_time.strftime("%H:%M")
            %br
            = "Nom: " + booking.name
            %br
            - if booking.phone?
              = "Tel.: " + booking.phone
              %br
            = "Email: " + booking.email
            %br
            = link_to "Modifier", edit_admin_booking_path(booking)
            = link_to "Supprimer", admin_booking_path(booking), method: :delete, data: {confirm: "Êtes-vous sûr?"}

app/views/bookings/_calendar.haml
.container
  .simple-calendar
    = week_calendar events: @bookings do |date, bookings|
      = date
      - bookings.each do |booking|
        %div
          - if admin_user_signed_in?
            = booking.name
          - else
            %strong= "Réservé"
          = booking.start_time.strftime("%H:%M")

app/views/bookings/_form.haml
= form_with(model: booking, local: true) do |form|
  - if @booking.errors.any?
    #error_explanation
      %h2
        Votre rendez-vous ne peut être enregistré.
      %ul
        - @booking.errors.each do |attr, msg|
          %li= msg
      %br

  .field
    = form.label :nom
    = form.text_field :name, :required => true
  .field
    = form.label :numéro
    = form.text_field :phone
  .field
    = form.label :email
    = form.email_field :email, :required => true
  .field
    = form.label :plage_horaire
    = form.datetime_select :start_time, :minute_step => 15,
      :start_hour => 17, :end_hour => 20,
      :start_year => Date.today.year, :end_year => Date.today.year
  .actions
    = form.submit "Ajoutez à l'horaire", class: 'button is-large is-primary'

app/views/bookings/confirmation.haml
%section#rendez-vous
  .container
    .content
    %p#notice= notice
    %h1.title.has-text-primary.has-text-centered.has-lines
      VOTRE RENDEZ-VOUS A ÉTÉ AJOUTÉ À L'HORAIRE
    %p
      À bientôt!

    = link_to 'Retour', bookings_path

app/views/bookings/edit.haml
%section#rendez-vous
  .container
    .content
      %p#notice= notice
      %h1.title.has-text-primary.has-text-centered.has-lines
        Modifier votre rendez-vous
      = render 'form', booking: @booking
      = link_to 'Voir', @booking
      |
      \#{link_to 'Retour', bookings_path}

app/views/bookings/index.haml
%section#rendez-vous-index
  .container
    .content
      - if notice
        %p#notice.has-text-primary.is-size-3= notice
      %h1.title.has-text-primary.has-text-centered.has-lines
        PRENEZ RENDEZ-VOUS
      %p.has-text-centered
        Inscrivez vous à l'horaire afin de nous permettre de mieux vous servir.
      %p.has-text-centered Le Centre de Distribution Alimentaire est ouvert 7 jours sur 7, de 5 heure à 21 heure.
      = link_to "S'inscrire à l'horaire", new_booking_path, class: "button is-primary is-center is-large"

  = render partial: 'calendar', locals: { booking: @bookings }

app/views/bookings/new.haml
%section#rendez-vous-form
  .container
    .content
      %p#notice= notice
      %h1.title.has-text-primary.has-text-centered.has-lines
        NOUVEAU RENDEZ-VOUS
      = render partial: 'form', locals: { booking: @booking }
      = link_to 'Retour', bookings_path

app/views/bookings/show.haml
%section#rendez-vous
  .container
    .content
    %p#notice= notice
    %h1.title.has-text-primary.has-text-centered.has-lines
      VOTRE RENDEZ-VOUS A ÉTÉ AJOUTÉ À L'HORAIRE
    %p
      %strong Nom:
      = @booking.name
    %p
      %strong Date:
      = @booking.start_time
    %p
      %strong Email:
      = @booking.email
    %p
      - if !(@booking.phone.empty?)
        %strong Numéro de téléphone:
        = @booking.phone

    %br

    = link_to 'Modifier', edit_booking_path(@booking)
    |
    \#{link_to 'Retour', bookings_path}

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}/

    %title 3R Québec

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'shared/navbar'

    = yield

    = render 'shared/don'
    = render 'shared/partenaires'

    = render 'shared/footer'

app/views/pages/about.haml
#apropos
  = render 'shared/about'
  = render 'shared/mission'
  = render 'shared/carousel'

app/views/pages/ca.haml
%section.section#ca
  .container
    .content.has-text-centered
      %h1.title.has-text-primary.has-lines
        NOTRE CONSEIL D'ADMINISTRATION

      .columns
        .column.is-4
          %figure.image.is-square
            = image_tag 'ca/simon.png'
          %h2.subtitle Simon Boudreau

        .column.is-4
          %figure.image.is-square
            = image_tag '3rqc-logo-400x400.png'
          = link_to 'COMMUNIQUEZ AVEC NOTRE C.A.', root_path(anchor: 'contact_form'), class: 'button is-primary is-rounded is-medium'

        .column.is-4
          %figure.image.is-square
            = image_tag 'ca/denis.png'
          %h2.subtitle Denis Poitras

      .columns
        .column.is-4
          %figure.image.is-square
            = image_tag 'ca/dave.png'
          %h2.subtitle Dave Langevin

        .column.is-4
          %figure.image.is-square
            = image_tag 'ca/christian.png'
          %h2.subtitle Christian Bolduc

        .column.is-4
          %figure.image.is-square
            = image_tag 'ca/bounthao.png'
          %h2.subtitle Bounthao Thammavongsa

app/views/pages/home.haml
#home
  %section.hero.is-medium#accueil
    .hero-body
      .container
        .has-text-centered
          = image_tag '3rqc-logo-400x400.png', width: 400, height: 400
          %h1.title Réduction - Réemploi - Recyclage
          .buttons.is-centered
            = link_to "S'inscrire aux distributions", root_path(anchor: 'distribution'), class: 'button is-primary is-medium is-rounded'
            = link_to "Centre de Transbordement", root_path(anchor: 'transbordement'), class: 'button is-primary is-medium is-rounded'
            = link_to "Boîtes RÉCUP-TOUT", root_path(anchor: 'boites'), class: 'button is-primary is-medium is-rounded'

  = render 'pages/home/help'
  = render 'pages/home/distribution'
  = render 'pages/home/transbordement'
  = render 'pages/home/boites'
  = render 'pages/home/contact'

app/views/pages/home/_about.haml
%section.section.has-background-primary#about
  .container
    .content
      %h1.title.has-text-centered.has-text-white.has-lines
        À PROPOS DE NOUS

      .columns.is-marginless
        .column.is-paddingless
          .padding-box#reduce
            %h2.subtitle.has-text-centered.has-text-white
              RÉDUCTION
            %p.has-text-light
              Nous vivons dans une société de surconsommation et d'abondance. Nous
              nous efforçons d'éduquer les gens à une meilleure gestion de leur
              consommation; ce qui commence par la réduction de cette même
              consommation.

        .column.is-paddingless
          .padding-box#reuse
            %h2.subtitle.has-text-centered.has-text-white
              RÉEMPLOI
            %p.has-text-light
              Nous priorisons le réemploi de la matière bien avant le recyclage.
              Le coût énergétique du recyclage dépasse largement les coûts
              énergétiques reliés au réemploi. Ce dernier est une cause à effet de
              réduction de la consommation.

        .column.is-paddingless
          .padding-box#recycle
            %h2.subtitle.has-text-centered.has-text-white
              RECYCLAGE
            %p.has-text-light
              En fin de vie, les différents objets traités chez 3R trouvent
              souvent leur place dans le recyclage plutôt qu'à l'enfouissement.
              Voila la fin de la boucle du cycle 3R.

app/views/pages/home/_boites.haml
%section.section#boites
  .container
    .content.has-text-centered
      %h1.has-text-primary.title.has-lines
        LES BOÎTES RÉCUP-TOUT
      .columns
        .column.is-3
        .column.is-6
          %p.font-22
            Les boîtes RÉCUP-TOUT servent à recueillir les dons matériels,
            les vêtements et les autres articles usagés
            à des fins de réemploi ou de recyclage.
          %p.font-22
            Vous pouvez trouver les boîtes aux quatre coins de la région,
            tel qu'indiqué sur la carte ci-dessous.
          = link_to "Signalez le ramassage d'une boîte", root_path(anchor:'contact_form'), class: 'button is-primary is-medium is-rounded'
        .column.is-3

= render "shared/maps"

app/views/pages/home/_contact.haml
%section.section#contact
  .container
    .content.has-text-centered
      %h1.has-text-primary.title.has-lines
        CONTACT

      %h2.subtitle Dépôt d'encombrants (RENDEZ-VOUS SEULEMENT)

      %p.font-22 NOUS N'ACCEPTERONS PLUS LES DÉPÔTS DE MEUBLES ET MATELAS.

      %p.font-22 MERCI DE VOTRE COLLABORATION ET VOTRE SUPPORT!

      %h2.subtitle 3R Québec Inc
      %p
        %a{href: 'tel:8196358899'} (819) 635-8899
      %br
      %br


      .columns
        .column
          .centre_information
            = image_tag "trash.svg"
            %h2.title
              CENTRE DE TRANSBORDEMENT
            .address
              600 Maloney Est (Pépinière Emery), Gatineau, Qc
            %br
            %p
              Lundi-Vendredi &nbsp;:&emsp; 9am-2pm
              %br
              Samedi &nbsp;:&emsp; Fermé
              %br
              Dimanche &nbsp;:&emsp; Fermé

        .column
          .centre_information
            = image_tag "food-delivery.svg"
            %h2.title
              CENTRE DE DISTRIBUTION ALIMENTAIRE
            .address
              373-A Notre Dame, Gatineau, Qc
            %br
            %p
              7 jours/semaine &nbsp;:&emsp; 5pm-9pm
        .column
          .centre_information
            = image_tag "paper-bag.svg"
            %h2.title
              CENTRE DE TRIAGE ALIMENTAIRE
            .address
              380 Notre Dame, Gatineau


= render 'shared/contact_form'

app/views/pages/home/_distribution.haml
%section.section#distribution
  .container
    .content
      %figure.image.is-3by1.is-hidden-mobile
        = image_tag 'distribution.png'

      %h1.title.has-text-primary.has-text-centered.has-lines
        DISTRIBUTION DE SURPLUS ALIMENTAIRES

      .columns
        .column.is-7
          .padding-box
            %h2.subtitle Qui peut s'inscrire?
            %p.font-22
              Tout le monde qui veux participer à la réduction de la consommation à
              la source, le réemploi des invendus d’épiceries, une meilleure gestion
              de nos matières résiduelles au Québec ou tout simplement pour
              encourager 3R Québec à demeurer un chef de file en GMR.

        .column.is-5
          .padding-box
            %h2.subtitle.has-text-centered Comment peut-on s'inscrire?
            %p.has-text-centered
              Téléphonez-nous au
              %strong 819-635-8899 ext 102
              %br/
              %em ou
              %br/
              Cliquez ci-dessous&nbsp;:
            .buttons.is-centered
              = link_to "S'inscrire aux distributions", new_user_registration_path, class: 'button is-primary is-medium is-rounded'

app/views/pages/home/_help.haml
%section.section.has-background-primary#help
  .container
    .content
      %h1.title.has-text-centered.has-text-white.has-lines
        Aide recherchée
      .columns
        .column.is-3
        .column.is-6
          %p.has-text-centered.has-text-light.font-22
            Vous voulez supporter la cause de 3R Québec, vous impliquer et venir
            aider des familles dans le besoin? Laissez-nous votre courriel pour
            recevoir de plus amples informations sur la façon dont vous pouvez faire
            une différence!
          %br

          .field.is-grouped
            .control.is-expanded
              %input.input{type: 'email', placeholder: 'Email'}
            .control
              %input.button.is-primary.is-rounded{type: 'submit', value: 'JE VEUX AIDER!'}
        .column.is-3

app/views/pages/home/_transbordement.haml
%section.section.is-paddingless#transbordement
  .columns.is-marginless
    .column.is-paddingless
      .content
        %h1.has-text-primary.title
          Encombrants acceptés au centre de transbordement de 3R&nbsp;:
        %ul.font-22
          %li Appareils électriques ou à pile
          %li Appareils informatiques, imprimantes, cartouches d'encre (dans un sac)
          %li Téléphones Cellulaires & accessoires
          %li Fils, câblage, lumières de noël, piles, batteries
          %li Métaux ferreux et non ferreux
          %li Canettes, bouteilles consignées, bouteilles de vin
          %li Outils, quincaillerie, plomberie
          %li Vêtements, souliers, literie, ceinture
          %li Bijoux, montres, accessoires
          %li Articles de maison (rideau, cadres, tapis, instruments de musique, décoration, etc)
          %li Vaisselle, ustensil, poêles, chaudrons
          %li Jouets, jeux, articles scolaires
          %li Article de bébé,siège de voiture, poussette
          %li Articles de sport
        %br

        %p.has-text-centered
          %strong.font-22
            VEUILLEZ NOTER QUE NOUS N'EFFECTUONS PLUS DE RAMASSAGES À DOMICILE
            POUR LES PARTICULIERS.

        %p.has-text-centered
          %strong.font-22
            POUR LE RAMASSAGE DE VOS GROS ENCOMBRANTS, VEUILLEZ COMMUNIQUER AVEC
            LE
            %br/
            %a{href: 'tel:311'}
              %i.fas.fa-phone
              3-1-1

        %p.has-text-centered
          %strong.font-22
            POUR TOUT AUTRE DEMANDE, SVP COMMUNIQUEZ AVEC NOUS
            %br/
            %a{href: 'tel:8196358899'}
              %i.fas.fa-phone
              819-635-8899

    .column.is-paddingless
      = image_tag 'transbordement.png'

app/views/pages/rendez_vous.haml
#rendez-vous
  %section
    = month_calendar do |date|
      = date

app/views/shared/_about.haml
%section.section#about
  .container
    .content
      %h1.title.has-text-centered.has-lines
        À PROPOS DE NOUS

      .columns.is-marginless
        .column
          .padding-box#reduce
            %h2.subtitle.has-text-centered.has-text-white
              RÉDUCTION
            %p.has-text-light
              Nous vivons dans une société de surconsommation et d'abondance. Nous
              nous efforçons d'éduquer les gens à une meilleure gestion de leur
              consommation; ce qui commence par la réduction de cette même
              consommation.

        .column
          .padding-box#reuse
            %h2.subtitle.has-text-centered.has-text-white
              RÉEMPLOI
            %p.has-text-light
              Nous priorisons le réemploi de la matière bien avant le recyclage.
              Le coût énergétique du recyclage dépasse largement les coûts
              énergétiques reliés au réemploi. Ce dernier est une cause à effet de
              réduction de la consommation.

        .column
          .padding-box#recycle
            %h2.subtitle.has-text-centered.has-text-white
              RECYCLAGE
            %p.has-text-light
              En fin de vie, les différents objets traités chez 3R trouvent
              souvent leur place dans le recyclage plutôt qu'à l'enfouissement.
              Voila la fin de la boucle du cycle 3R.

app/views/shared/_carousel.haml
%section.section#carousel
  .container
    .content.has-text-centered
      %h1.has-text-primary.title.has-lines
        PHOTOS
      #images_carousel
        - @images.each do |image|
          .image_carousel
            = image_tag image

app/views/shared/_contact_form.haml
%section.section#contact_form.is-paddingless
  .container
    .content
      %h1.title.has-text-centered.has-text-white.has-lines
        Écrivez-nous!
      .form-wrap
        = form_tag(send_mail_path) do
          .columns
            .column
              .field
                %input.input.is-medium{:name => "name", :type => "text", :placeholder => "Nom", :required => true}
              .field
                %input.input.is-medium{:name => "address", :type => "text", :placeholder => "Adresse"}
              .field
                %input.input.is-medium{:name => "phone", :type => "text", :placeholder => "Numéro de téléphone"}
              .field
                %input.input.is-medium{:name => "email", :type => "email", :placeholder => "Email", :required => true}
            .column
              .field
                %textarea.textarea.is-medium{:name => "message", :type => "text", :placeholder => "Message", :required => true}
          .control
            %input.button.is-primary-inverted.is-medium.is-rounded{:type => 'submit', :value => "ENVOYEZ"}
      - if notice
        %p#notice.has-text-light.has-text-weight-bold.is-size-3= notice

app/views/shared/_don.haml
%section.section.is-paddingless#don
  .columns.is-marginless
    .column.is-paddingless
      .homepage_image
      -# = image_tag 'don.png', class: "homepage_image"



    .column.is-paddingless
      .content
        %h1.has-text-primary.title SUPPORTEZ NOTRE CAUSE
        %p
          Votre support et contributions sont très importantes pour nous afin
          de soutenir la lutte au gaspillage en tout genre.
        %p
          Merci de donner généreusement en argent, en temps ou dans l'une
          de nos boites RÉCUP-TOUT géolocalisées plus bas sur cette page.
        %p
          De nous tous à 3R Québec, un gros merci!
        %br

        %form{:action => "https://www.paypal.com/cgi-bin/webscr", :method => "post", :target => "_top"}
          %input{:name => "cmd", :type => "hidden", :value => "_donations"}/
          %input{:name => "business", :type => "hidden", :value => "simonboudreau77@hotmail.com"}/
          %input{:name => "item_name", :type => "hidden", :value => "3R Quebec Inc"}/
          %input{:name => "currency_code", :type => "hidden", :value => "CAD"}/
          %input.button.is-primary.is-large.is-rounded{:type => 'submit', :value => "DONS EN ARGENT"}

          = image_tag 'cc-badges.png', class: "cc-badges is-center"

app/views/shared/_footer.haml
%footer.footer.has-background-black
  .content.has-text-centered
    %p.has-text-light
      = link_to 'https://www.facebook.com/3rquebec' do
        %i.fab.fa-facebook
        &nbsp;
        Suivez-nous sur Facebook!
    %p.has-text-light Copyright &copy; 2020 3R Québec inc. Tous droits réservés.
    %small.has-text-light Fait avec ❤️ par #{link_to 'Gauthier logiciel enr.', 'https://gauthier.software'}

app/views/shared/_maps.haml
%section.section.is-paddingless#maps
  .overlay{:onclick => "style.pointerEvents='none'"}
  %iframe{:src => "https://www.google.com/maps/d/embed?mid=1y3Ouzfc8hOv2Jw6olTHXEpft6iNOb_F_", :width => "100%"}

app/views/shared/_mission.haml
%section.section.is-paddingless#mission
  .columns.is-marginless
    .column.is-paddingless
      .content
        %h1.has-text-primary.title
          MISSION ET OBJECTIFS

        %h2.subtitle MISSION

        %ul.font-22
          %li
            Participer à la réduction des déchets voués à l'enfouissement

          %li
            Récupérer des objets autrement voués à l'élimination dans le but de
            valoriser par le réemploi ou le recyclage

          %li
            Supporter nos partenaires et nos organismes à but non lucratifs
            locaux dans leurs opérations

        %h2.subtitle OBJECTIFS

        %ul.font-22
          %li
            Valoriser au moins 85% des matières recupérées

          %li
            Offrir des articles gratuits pour nos organismes à but non lucratifs
            locaux

          %li
            Réduire les tonnes de matières résiduelles vouées à l'enfouissement

          %li
            Créer des emplois

    .column.is-paddingless
      = image_tag 'mission.png'

app/views/shared/_navbar.haml
%nav.navbar.is-primary{"aria-label": "main navigation", role: "navigation"}
  .container
    .navbar-brand
      = link_to '3R QUÉBEC', root_path, class: 'navbar-item'

      %a.navbar-burger.burger{"aria-expanded": "false", "aria-label": "menu", data: { target: "main-navbar" }, role: "button" }
        %span{"aria-hidden" => "true"}
        %span{"aria-hidden" => "true"}
        %span{"aria-hidden" => "true"}

    #main-navbar.navbar-menu
      .navbar-start
        = link_to 'Accueil', root_path, class: 'navbar-item'
        = link_to 'Partenaires', root_path(anchor: 'partenaires'), class: 'navbar-item'
        = link_to 'C.A.', ca_path, class: 'navbar-item'
        = link_to 'À propos de nous', a_propos_de_nous_path, class: 'navbar-item'
        = link_to 'Prendre rendez-vous', bookings_path, class: 'navbar-item'

      .navbar-end
        = link_to admin_root_path, class: 'navbar-item' do
          %i.fas.fa-sign-in-alt
          &nbsp;
          Se connecter

app/views/shared/_partenaires.haml
%section.section#partenaires
  .container
    .content.has-text-centered
      %h1.title.has-text-primary.has-lines
        MERCI À NOS PARTENAIRES

      .columns
        .column.is-3
          = link_to 'https://www.ssvp-mtl.org/fr' do
            %figure.image.is-square
              = image_tag 'partenaires/stvincent.png'

        .column.is-3
          = link_to 'http://legiteami.org/' do
            %figure.image.is-square
              = image_tag 'partenaires/legiteami.png'

        .column.is-3
          = link_to 'http://www.environnement.gouv.qc.ca/' do
            %figure.image.is-square
              = image_tag 'partenaires/chgmentclimatqc.png'

        .column.is-3
          = link_to 'https://coalitionavenirquebec.org/fr/blog/equipe/mathieu-levesque/' do
            %figure.image.is-square
              = image_tag 'partenaires/matlevesque.png'

      .columns
        .column.is-3
          = link_to 'https://depanneursylvestre.org/' do
            %figure.image.is-square
              = image_tag 'partenaires/sylvestre.png'

        .column.is-3
          = link_to 'http://enviroeducaction.org/' do
            %figure.image.is-square
              = image_tag 'partenaires/enviroeducaction.png'

        .column.is-3
          = link_to 'http://www.gatineau.ca/' do
            %figure.image.is-square
              = image_tag 'partenaires/gatineau.png'

        .column.is-3
          = link_to 'https://www.cantley.ca/' do
            %figure.image.is-square
              = image_tag 'partenaires/cantley.png'

      .columns
        .column.is-3
          = link_to 'http://www.kazabazua.ca/' do
            %figure.image.is-square
              = image_tag 'partenaires/kazabazua.png'

        .column.is-3
          = link_to 'http://www.metro.ca/' do
            %figure.image.is-square
              = image_tag 'partenaires/metro.png'

        .column.is-3
          = link_to 'https://www.bmo.com' do
            %figure.image.is-square
              = image_tag 'partenaires/bmo.png'

        .column.is-3
          = link_to 'https://www.provigo.ca/' do
            %figure.image.is-square
              = image_tag 'partenaires/provigo.png'

      .columns
        .column.is-3
          = link_to 'https://gauthier.software/' do
            %figure.image.is-square
              = image_tag 'partenaires/gs.png'

        .column.is-3

        .column.is-3

        .column.is-3